[project]
name = "QuickeR"
version = "1.0.0"
license = { text = "MIT" }
description = ""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Unax Martinez Llorente (ChoiceZero)", email = "unaxmarti2009@gmail.com" }
]
dependencies = [
    "flet>=0.85.2",
    "flet-color-pickers==0.85.3",
    "numpy",
    "opencv-python",
    "pillow",
    "qrcode"
]

[dependency-groups]
dev = [
    "flet-cli>=0.85.2",
    "flet-desktop>=0.85.2",
    "flet-web>=0.85.2",
    #"watchdog>=4.0.0"
]

[tool.flet]
desktop_flavor = "light"    # Change to "full" to use flet-audio and flet-video
org = "com.mycompany"
product = "QuickeR"
company = "Unax Martinez Llorente"
copyright = "MIT License"

[tool.flet.app]
path = "src"

[tool.flet.package]
exclude = [
    ".venv",          
    "venv",
    "__pycache__",    
    "*.pyc",
    "tests",         
    "documentos",  
    "README.md",
    ".gitignore",   
    ".git",
    "src/pinned_qr_codes",  
    "src/qr_codes"           
]